import { ROUTES } from '../../../constants/routes';

export enum ENTITY_ACTION {
  CREATE_FORM = 'createForm',
  EDIT_FORM = 'editForm',
  DELETE_FORM = 'deleteForm',
  CREATE_PROCESS = 'createProcess',
  EDIT_PROCESS = 'editProcess',
  DELETE_PROCESS = 'deleteProcess',
  CREATE_I18N = 'createI18n',
  EDIT_I18N = 'editI18n',
  DELETE_I18N = 'deleteI18n',
}

export const getActionPath = (isMaster: boolean) => (isMaster ? 'successMasterPath' : 'successCandidatePath');

export const ENTITIES_ACTION_MAP = {
  [ENTITY_ACTION.CREATE_FORM]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionCreateForm',
    conflictModalDescriptionMaster: '',
    conflictModalDescriptionCandidate: '',
    conflictModalTextButton: '',
    path: ROUTES.CREATE_FORM,
    successCandidatePath: ROUTES.EDIT_FORM,
    successMasterPath: ROUTES.FORM_LIST,
  },
  [ENTITY_ACTION.EDIT_FORM]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionEditForm',
    conflictModalDescriptionMaster: 'pages~editForm.modal.conflict.descriptionMaster',
    conflictModalDescriptionCandidate: 'pages~editForm.modal.conflict.descriptionCandidate',
    conflictModalTextButton: 'pages~editForm.modal.conflict.textButton',
    path: ROUTES.EDIT_FORM,
    successCandidatePath: ROUTES.EDIT_FORM,
    successMasterPath: ROUTES.FORM_LIST,
  },
  [ENTITY_ACTION.DELETE_FORM]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionDeleteForm',
    conflictModalDescriptionMaster: 'components~modal.conflictDeleteForm.descriptionMaster',
    conflictModalDescriptionCandidate: 'components~modal.conflictDeleteForm.descriptionCandidate',
    conflictModalTextButton: 'components~modal.conflictDeleteForm.textButton',
    path: '',
    successCandidatePath: ROUTES.HOME,
    successMasterPath: ROUTES.FORM_LIST,
  },
  [ENTITY_ACTION.CREATE_PROCESS]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionCreateProcess',
    conflictModalDescriptionMaster: '',
    conflictModalDescriptionCandidate: '',
    conflictModalTextButton: '',
    path: ROUTES.CREATE_PROCESS,
    successCandidatePath: ROUTES.EDIT_PROCESS,
    successMasterPath: ROUTES.PROCESS_LIST,
  },
  [ENTITY_ACTION.EDIT_PROCESS]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionEditProcess',
    conflictModalDescriptionMaster: 'pages~editProcess.modal.conflict.descriptionMaster',
    conflictModalDescriptionCandidate: 'pages~editProcess.modal.conflict.descriptionCandidate',
    conflictModalTextButton: 'pages~editProcess.modal.conflict.textButton',
    path: ROUTES.EDIT_PROCESS,
    successCandidatePath: ROUTES.EDIT_PROCESS,
    successMasterPath: ROUTES.PROCESS_LIST,
  },
  [ENTITY_ACTION.DELETE_PROCESS]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionDeleteProcess',
    conflictModalDescriptionMaster: 'components~modal.conflictDeleteProcess.descriptionMaster',
    conflictModalDescriptionCandidate: 'components~modal.conflictDeleteProcess.descriptionCandidate',
    conflictModalTextButton: 'components~modal.conflictDeleteProcess.textButton',
    path: '',
    successCandidatePath: ROUTES.HOME,
    successMasterPath: ROUTES.PROCESS_LIST,
  },
  [ENTITY_ACTION.CREATE_I18N]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionCreateI18n',
    conflictModalDescriptionMaster: '',
    conflictModalDescriptionCandidate: '',
    conflictModalTextButton: '',
    path: ROUTES.I18N_LIST,
    successCandidatePath: ROUTES.I18N_LIST,
    successMasterPath: ROUTES.I18N_LIST,
  },
  [ENTITY_ACTION.EDIT_I18N]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionEditI18n',
    conflictModalDescriptionMaster: 'components~modal.conflictEditI18n.descriptionMaster',
    conflictModalDescriptionCandidate: 'components~modal.conflictEditI18n.descriptionCandidate',
    conflictModalTextButton: 'components~modal.conflictEditI18n.textButton',
    path: ROUTES.I18N_LIST,
    successCandidatePath: ROUTES.I18N_LIST,
    successMasterPath: ROUTES.I18N_LIST,
  },
  [ENTITY_ACTION.DELETE_I18N]: {
    description: 'components~modal.whereToSaveChanges.text.descriptionDeleteI18n',
    conflictModalDescriptionMaster: 'components~modal.conflictDeleteI18n.descriptionMaster',
    conflictModalDescriptionCandidate: 'components~modal.conflictDeleteI18n.descriptionCandidate',
    conflictModalTextButton: 'components~modal.conflictDeleteI18n.textButton',
    path: '',
    successCandidatePath: ROUTES.HOME,
    successMasterPath: ROUTES.I18N_LIST,
  },
};
